defaults:
  - _self_
  - agent: map/PointNet_SingleFrame
  - benchmark: map/maniskill_map_cameraloss

seed: 0
device: cuda:0

task_name: StackCube-v1
camera_name: base_camera
image_size: 1024

project_root: ${oc.env:MAPPOLICY_ROOT,your_path_to_project_root}
dataset_dir: ${project_root}/data/maniskill/${task_name}_${camera_name}.zarr

dataloader:
  batch_size: 256
  num_workers: 4
  shuffle: True
  drop_last: True
  pin_memory: True

train:
  gradient_accumulate_every: 1
  clip_grad_value: 1.0
  learning_rate: 4e-4
  num_epochs: 300
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0
  scheduler_instantiate_config:
    _target_: mappolicy.helper.pytorch.Optimizers.get_warmup_cosine_annealing_scheduler
    num_warmup_epochs: 20
    num_epochs: ${train.num_epochs}
    warmup_factor: 0.01
    eta_min: 1.0e-6

evaluation:
  num_skip_epochs: 0
  validation_frequency_epochs: 5
  save_best_model: True
  save_point_clouds: True
  save_num_batches: 2
  save_num_samples_per_batch: 4

hydra:
  run:
    dir: outputs/map/${agent.name}/${task_name}_${camera_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: map_${agent.name}_${task_name}_${camera_name}